server:
  port: 8080
  tomcat:
    basedir: /temp
spring:
  application:
    name: wslog
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/

logging:
  file:
    path: ./logs