spring:
  application:
    name: canal-sync
server:
  port: 8001
# canal相关配置
# subscribe 过滤规则
# 1）  所有：.*   or  .*\\..*
# 2）  "test"库下所有表： test\\..*
# 3）  "test"下的以"sys"打头的表：test\\.sys.*
# 4）  "test"下的具体一张表：test.blog   blog表
# 5）  多个规则组合使用：test\\..*,test.sys_user,test.sys_role (逗号分隔)
canal:
  host: 172.16.7.100
  port: 3306
  destination: demo
  username:
  password:
  subscribe: .*
  batchSize: 1000
